name: reelai
description: A TikTok clone app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_functions: ^4.5.8
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  
  # Camera and Video
  camera: ^0.10.5+5
  video_player: ^2.8.1
  
  # Utils
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0  # For navigation
  provider: ^6.1.1    # For state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 