name: reelai
description: A TikTok clone app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_functions: ^4.6.9
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9
  firebase_app_check: ^0.2.1+14
  
  # Camera and Video
  camera: ^0.10.5+5
  media_kit: ^1.1.10                  # Core package
  media_kit_video: ^1.2.4             # For video rendering
  media_kit_libs_video: ^1.0.4        # Native video dependencies
  visibility_detector: ^0.4.0+2
  
  # Utils
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0  # For navigation
  provider: ^6.1.1    # For state management
  http: ^1.1.0
  shared_preferences: ^2.2.2
  app_links: ^3.4.5
  path: ^1.8.3
  video_compress: ^3.1.2  # Add video compression package
  image_picker: ^1.0.7
  uuid: ^4.3.3  # Add UUID package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/